sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rohitdockeryes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rohitdockeryes/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react2'
  env: 'Dockerreact2-env'
  bucket_name: 'elasticbeanstalk-us-east-1-004465573805'
  bucket_path: 'docker-react2'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
